from dataclasses import dataclass

@dataclass(frozen=True)
class Conjugation:
    base: str
    past_participle: str
    simple_past: str
    present_participle: str

_conjugation_map = {
    # A
    "abide": Conjugation(base="abide", past_participle="abided", simple_past="abided", present_participle="abiding"),
    "absorb": Conjugation(base="absorb", past_participle="absorbed", simple_past="absorbed", present_participle="absorbing"),
    "accept": Conjugation(base="accept", past_participle="accepted", simple_past="accepted", present_participle="accepting"),
    "access": Conjugation(base="access", past_participle="accessed", simple_past="accessed", present_participle="accessing"),
    "accompany": Conjugation(base="accompany", past_participle="accompanied", simple_past="accompanied", present_participle="accompanying"),
    "account": Conjugation(base="account", past_participle="accounted", simple_past="accounted", present_participle="accounting"),
    "accuse": Conjugation(base="accuse", past_participle="accused", simple_past="accused", present_participle="accusing"),
    "achieve": Conjugation(base="achieve", past_participle="achieved", simple_past="achieved", present_participle="achieving"),
    "acknowledge": Conjugation(base="acknowledge", past_participle="acknowledged", simple_past="acknowledged", present_participle="acknowledging"),
    "acquire": Conjugation(base="acquire", past_participle="acquired", simple_past="acquired", present_participle="acquiring"),
    "act": Conjugation(base="act", past_participle="acted", simple_past="acted", present_participle="acting"),
    "adapt": Conjugation(base="adapt", past_participle="adapted", simple_past="adapted", present_participle="adapting"),
    "add": Conjugation(base="add", past_participle="added", simple_past="added", present_participle="adding"),
    "address": Conjugation(base="address", past_participle="addressed", simple_past="addressed", present_participle="addressing"),
    "admire": Conjugation(base="admire", past_participle="admired", simple_past="admired", present_participle="admiring"),
    "admit": Conjugation(base="admit", past_participle="admitted", simple_past="admitted", present_participle="admitting"),
    "adopt": Conjugation(base="adopt", past_participle="adopted", simple_past="adopted", present_participle="adopting"),
    "advise": Conjugation(base="advise", past_participle="advised", simple_past="advised", present_participle="advising"),
    "affect": Conjugation(base="affect", past_participle="affected", simple_past="affected", present_participle="affecting"),
    "age": Conjugation(base="age", past_participle="aged", simple_past="aged", present_participle="aging"),
    "agree": Conjugation(base="agree", past_participle="agreed", simple_past="agreed", present_participle="agreeing"),
    "aim": Conjugation(base="aim", past_participle="aimed", simple_past="aimed", present_participle="aiming"),
    "alert": Conjugation(base="alert", past_participle="alerted", simple_past="alerted", present_participle="alerting"),
    "allow": Conjugation(base="allow", past_participle="allowed", simple_past="allowed", present_participle="allowing"),
    "alter": Conjugation(base="alter", past_participle="altered", simple_past="altered", present_participle="altering"),
    "analyse": Conjugation(base="analyse", past_participle="analysed", simple_past="analysed", present_participle="analysing"),
    "analyze": Conjugation(base="analyze", past_participle="analyzed", simple_past="analyzed", present_participle="analyzing"),
    "announce": Conjugation(base="announce", past_participle="announced", simple_past="announced", present_participle="announcing"),
    "answer": Conjugation(base="answer", past_participle="answered", simple_past="answered", present_participle="answering"),
    "appear": Conjugation(base="appear", past_participle="appeared", simple_past="appeared", present_participle="appearing"),
    "apply": Conjugation(base="apply", past_participle="applied", simple_past="applied", present_participle="applying"),
    "approach": Conjugation(base="approach", past_participle="approached", simple_past="approached", present_participle="approaching"),
    "approve": Conjugation(base="approve", past_participle="approved", simple_past="approved", present_participle="approving"),
    "argue": Conjugation(base="argue", past_participle="argued", simple_past="argued", present_participle="arguing"),
    "arise": Conjugation(base="arise", past_participle="arisen", simple_past="arose", present_participle="arising"),
    "arrange": Conjugation(base="arrange", past_participle="arranged", simple_past="arranged", present_participle="arranging"),
    "arrest": Conjugation(base="arrest", past_participle="arrested", simple_past="arrested", present_participle="arresting"),
    "arrive": Conjugation(base="arrive", past_participle="arrived", simple_past="arrived", present_participle="arriving"),
    "ask": Conjugation(base="ask", past_participle="asked", simple_past="asked", present_participle="asking"),
    "assign": Conjugation(base="assign", past_participle="assigned", simple_past="assigned", present_participle="assigning"),
    "assist": Conjugation(base="assist", past_participle="assisted", simple_past="assisted", present_participle="assisting"),
    "assume": Conjugation(base="assume", past_participle="assumed", simple_past="assumed", present_participle="assuming"),
    "attach": Conjugation(base="attach", past_participle="attached", simple_past="attached", present_participle="attaching"),
    "attempt": Conjugation(base="attempt", past_participle="attempted", simple_past="attempted", present_participle="attempting"),
    "attend": Conjugation(base="attend", past_participle="attended", simple_past="attended", present_participle="attending"),
    "attract": Conjugation(base="attract", past_participle="attracted", simple_past="attracted", present_participle="attracting"),
    "authorise": Conjugation(base="authorise", past_participle="authorised", simple_past="authorised", present_participle="authorising"),
    "authorize": Conjugation(base="authorize", past_participle="authorized", simple_past="authorized", present_participle="authorizing"),
    "avoid": Conjugation(base="avoid", past_participle="avoided", simple_past="avoided", present_participle="avoiding"),
    "award": Conjugation(base="award", past_participle="awarded", simple_past="awarded", present_participle="awarding"),
    "awake": Conjugation(base="awake", past_participle="awoken", simple_past="awoke", present_participle="awaking"),
    # B
    "back": Conjugation(base="back", past_participle="backed", simple_past="backed", present_participle="backing"),
    "base": Conjugation(base="base", past_participle="based", simple_past="based", present_participle="basing"),
    "be": Conjugation(base="be", past_participle="been", simple_past="was", present_participle="being"),
    "beat": Conjugation(base="beat", past_participle="beaten", simple_past="beat", present_participle="beating"),
    "become": Conjugation(base="become", past_participle="become", simple_past="became", present_participle="becoming"),
    "begin": Conjugation(base="begin", past_participle="begun", simple_past="began", present_participle="beginning"),
    "believe": Conjugation(base="believe", past_participle="believed", simple_past="believed", present_participle="believing"),
    "belong": Conjugation(base="belong", past_participle="belonged", simple_past="belonged", present_participle="belonging"),
    "bend": Conjugation(base="bend", past_participle="bent", simple_past="bent", present_participle="bending"),
    "bind": Conjugation(base="bind", past_participle="bound", simple_past="bound", present_participle="binding"),
    "bite": Conjugation(base="bite", past_participle="bitten", simple_past="bit", present_participle="biting"),
    "bleed": Conjugation(base="bleed", past_participle="bled", simple_past="bled", present_participle="bleeding"),
    "block": Conjugation(base="block", past_participle="blocked", simple_past="blocked", present_participle="blocking"),
    "blow": Conjugation(base="blow", past_participle="blown", simple_past="blew", present_participle="blowing"),
    "borrow": Conjugation(base="borrow", past_participle="borrowed", simple_past="borrowed", present_participle="borrowing"),
    "break": Conjugation(base="break", past_participle="broken", simple_past="broke", present_participle="breaking"),
    "bring": Conjugation(base="bring", past_participle="brought", simple_past="brought", present_participle="bringing"),
    "broadcast": Conjugation(base="broadcast", past_participle="broadcast", simple_past="broadcast", present_participle="broadcasting"),
    "browse": Conjugation(base="browse", past_participle="browsed", simple_past="browsed", present_participle="browsing"),
    "build": Conjugation(base="build", past_participle="built", simple_past="built", present_participle="building"),
    "burn": Conjugation(base="burn", past_participle="burned", simple_past="burned", present_participle="burning"),
    "buy": Conjugation(base="buy", past_participle="bought", simple_past="bought", present_participle="buying"),
    # C
    "cache": Conjugation(base="cache", past_participle="cached", simple_past="cached", present_participle="caching"),
    "calculate": Conjugation(base="calculate", past_participle="calculated", simple_past="calculated", present_participle="calculating"),
    "call": Conjugation(base="call", past_participle="called", simple_past="called", present_participle="calling"),
    "cancel": Conjugation(base="cancel", past_participle="cancelled", simple_past="cancelled", present_participle="cancelling"),
    "capture": Conjugation(base="capture", past_participle="captured", simple_past="captured", present_participle="capturing"),
    "carry": Conjugation(base="carry", past_participle="carried", simple_past="carried", present_participle="carrying"),
    "cast": Conjugation(base="cast", past_participle="cast", simple_past="cast", present_participle="casting"),
    "catch": Conjugation(base="catch", past_participle="caught", simple_past="caught", present_participle="catching"),
    "cause": Conjugation(base="cause", past_participle="caused", simple_past="caused", present_participle="causing"),
    "change": Conjugation(base="change", past_participle="changed", simple_past="changed", present_participle="changing"),
    "charge": Conjugation(base="charge", past_participle="charged", simple_past="charged", present_participle="charging"),
    "check": Conjugation(base="check", past_participle="checked", simple_past="checked", present_participle="checking"),
    "choose": Conjugation(base="choose", past_participle="chosen", simple_past="chose", present_participle="choosing"),
    "cite": Conjugation(base="cite", past_participle="cited", simple_past="cited", present_participle="citing"),
    "claim": Conjugation(base="claim", past_participle="claimed", simple_past="claimed", present_participle="claiming"),
    "clean": Conjugation(base="clean", past_participle="cleaned", simple_past="cleaned", present_participle="cleaning"),
    "clear": Conjugation(base="clear", past_participle="cleared", simple_past="cleared", present_participle="clearing"),
    "click": Conjugation(base="click", past_participle="clicked", simple_past="clicked", present_participle="clicking"),
    "clone": Conjugation(base="clone", past_participle="cloned", simple_past="cloned", present_participle="cloning"),
    "close": Conjugation(base="close", past_participle="closed", simple_past="closed", present_participle="closing"),
    "code": Conjugation(base="code", past_participle="coded", simple_past="coded", present_participle="coding"),
    "collect": Conjugation(base="collect", past_participle="collected", simple_past="collected", present_participle="collecting"),
    "combine": Conjugation(base="combine", past_participle="combined", simple_past="combined", present_participle="combining"),
    "come": Conjugation(base="come", past_participle="come", simple_past="came", present_participle="coming"),
    "comment": Conjugation(base="comment", past_participle="commented", simple_past="commented", present_participle="commenting"),
    "commit": Conjugation(base="commit", past_participle="committed", simple_past="committed", present_participle="committing"),
    "compare": Conjugation(base="compare", past_participle="compared", simple_past="compared", present_participle="comparing"),
    "compile": Conjugation(base="compile", past_participle="compiled", simple_past="compiled", present_participle="compiling"),
    "complete": Conjugation(base="complete", past_participle="completed", simple_past="completed", present_participle="completing"),
    "compress": Conjugation(base="compress", past_participle="compressed", simple_past="compressed", present_participle="compressing"),
    "compute": Conjugation(base="compute", past_participle="computed", simple_past="computed", present_participle="computing"),
    "configure": Conjugation(base="configure", past_participle="configured", simple_past="configured", present_participle="configuring"),
    "confirm": Conjugation(base="confirm", past_participle="confirmed", simple_past="confirmed", present_participle="confirming"),
    "connect": Conjugation(base="connect", past_participle="connected", simple_past="connected", present_participle="connecting"),
    "consider": Conjugation(base="consider", past_participle="considered", simple_past="considered", present_participle="considering"),
    "consume": Conjugation(base="consume", past_participle="consumed", simple_past="consumed", present_participle="consuming"),
    "contain": Conjugation(base="contain", past_participle="contained", simple_past="contained", present_participle="containing"),
    "continue": Conjugation(base="continue", past_participle="continued", simple_past="continued", present_participle="continuing"),
    "control": Conjugation(base="control", past_participle="controlled", simple_past="controlled", present_participle="controlling"),
    "convert": Conjugation(base="convert", past_participle="converted", simple_past="converted", present_participle="converting"),
    "copy": Conjugation(base="copy", past_participle="copied", simple_past="copied", present_participle="copying"),
    "cost": Conjugation(base="cost", past_participle="cost", simple_past="cost", present_participle="costing"),
    "count": Conjugation(base="count", past_participle="counted", simple_past="counted", present_participle="counting"),
    "cover": Conjugation(base="cover", past_participle="covered", simple_past="covered", present_participle="covering"),
    "crash": Conjugation(base="crash", past_participle="crashed", simple_past="crashed", present_participle="crashing"),
    "create": Conjugation(base="create", past_participle="created", simple_past="created", present_participle="creating"),
    "crop": Conjugation(base="crop", past_participle="cropped", simple_past="cropped", present_participle="cropping"),
    "cut": Conjugation(base="cut", past_participle="cut", simple_past="cut", present_participle="cutting"),
    # D
    "damage": Conjugation(base="damage", past_participle="damaged", simple_past="damaged", present_participle="damaging"),
    "deal": Conjugation(base="deal", past_participle="dealt", simple_past="dealt", present_participle="dealing"),
    "debug": Conjugation(base="debug", past_participle="debugged", simple_past="debugged", present_participle="debugging"),
    "decide": Conjugation(base="decide", past_participle="decided", simple_past="decided", present_participle="deciding"),
    "decode": Conjugation(base="decode", past_participle="decoded", simple_past="decoded", present_participle="decoding"),
    "decompress": Conjugation(base="decompress", past_participle="decompressed", simple_past="decompressed", present_participle="decompressing"),
    "decrypt": Conjugation(base="decrypt", past_participle="decrypted", simple_past="decrypted", present_participle="decrypting"),
    "define": Conjugation(base="define", past_participle="defined", simple_past="defined", present_participle="defining"),
    "delete": Conjugation(base="delete", past_participle="deleted", simple_past="deleted", present_participle="deleting"),
    "deliver": Conjugation(base="deliver", past_participle="delivered", simple_past="delivered", present_participle="delivering"),
    "deny": Conjugation(base="deny", past_participle="denied", simple_past="denied", present_participle="denying"),
    "depend": Conjugation(base="depend", past_participle="depended", simple_past="depended", present_participle="depending"),
    "deploy": Conjugation(base="deploy", past_participle="deployed", simple_past="deployed", present_participle="deploying"),
    "describe": Conjugation(base="describe", past_participle="described", simple_past="described", present_participle="describing"),
    "design": Conjugation(base="design", past_participle="designed", simple_past="designed", present_participle="designing"),
    "detect": Conjugation(base="detect", past_participle="detected", simple_past="detected", present_participle="detecting"),
    "develop": Conjugation(base="develop", past_participle="developed", simple_past="developed", present_participle="developing"),
    "die": Conjugation(base="die", past_participle="died", simple_past="died", present_participle="dying"),
    "differ": Conjugation(base="differ", past_participle="differed", simple_past="differed", present_participle="differing"),
    "disable": Conjugation(base="disable", past_participle="disabled", simple_past="disabled", present_participle="disabling"),
    "disconnect": Conjugation(base="disconnect", past_participle="disconnected", simple_past="disconnected", present_participle="disconnecting"),
    "discover": Conjugation(base="discover", past_participle="discovered", simple_past="discovered", present_participle="discovering"),
    "display": Conjugation(base="display", past_participle="displayed", simple_past="displayed", present_participle="displaying"),
    "divide": Conjugation(base="divide", past_participle="divided", simple_past="divided", present_participle="dividing"),
    "do": Conjugation(base="do", past_participle="done", simple_past="did", present_participle="doing"),
    "document": Conjugation(base="document", past_participle="documented", simple_past="documented", present_participle="documenting"),
    "download": Conjugation(base="download", past_participle="downloaded", simple_past="downloaded", present_participle="downloading"),
    "draw": Conjugation(base="draw", past_participle="drawn", simple_past="drew", present_participle="drawing"),
    "drink": Conjugation(base="drink", past_participle="drunk", simple_past="drank", present_participle="drinking"),
    "drive": Conjugation(base="drive", past_participle="driven", simple_past="drove", present_participle="driving"),
    "drop": Conjugation(base="drop", past_participle="dropped", simple_past="dropped", present_participle="dropping"),
    # E
    "earn": Conjugation(base="earn", past_participle="earned", simple_past="earned", present_participle="earning"),
    "eat": Conjugation(base="eat", past_participle="eaten", simple_past="ate", present_participle="eating"),
    "edit": Conjugation(base="edit", past_participle="edited", simple_past="edited", present_participle="editing"),
    "emit": Conjugation(base="emit", past_participle="emitted", simple_past="emitted", present_participle="emitting"),
    "enable": Conjugation(base="enable", past_participle="enabled", simple_past="enabled", present_participle="enabling"),
    "encode": Conjugation(base="encode", past_participle="encoded", simple_past="encoded", present_participle="encoding"),
    "encrypt": Conjugation(base="encrypt", past_participle="encrypted", simple_past="encrypted", present_participle="encrypting"),
    "end": Conjugation(base="end", past_participle="ended", simple_past="ended", present_participle="ending"),
    "enter": Conjugation(base="enter", past_participle="entered", simple_past="entered", present_participle="entering"),
    "evaluate": Conjugation(base="evaluate", past_participle="evaluated", simple_past="evaluated", present_participle="evaluating"),
    "execute": Conjugation(base="execute", past_participle="executed", simple_past="executed", present_participle="executing"),
    "exist": Conjugation(base="exist", past_participle="existed", simple_past="existed", present_participle="existing"),
    "expect": Conjugation(base="expect", past_participle="expected", simple_past="expected", present_participle="expecting"),
    "explain": Conjugation(base="explain", past_participle="explained", simple_past="explained", present_participle="explaining"),
    "export": Conjugation(base="export", past_participle="exported", simple_past="exported", present_participle="exporting"),
    "extend": Conjugation(base="extend", past_participle="extended", simple_past="extended", present_participle="extending"),
    "extract": Conjugation(base="extract", past_participle="extracted", simple_past="extracted", present_participle="extracting"),
    # F
    "fail": Conjugation(base="fail", past_participle="failed", simple_past="failed", present_participle="failing"),
    "fall": Conjugation(base="fall", past_participle="fallen", simple_past="fell", present_participle="falling"),
    "feel": Conjugation(base="feel", past_participle="felt", simple_past="felt", present_participle="feeling"),
    "fetch": Conjugation(base="fetch", past_participle="fetched", simple_past="fetched", present_participle="fetching"),
    "fight": Conjugation(base="fight", past_participle="fought", simple_past="fought", present_participle="fighting"),
    "fill": Conjugation(base="fill", past_participle="filled", simple_past="filled", present_participle="filling"),
    "filter": Conjugation(base="filter", past_participle="filtered", simple_past="filtered", present_participle="filtering"),
    "find": Conjugation(base="find", past_participle="found", simple_past="found", present_participle="finding"),
    "finish": Conjugation(base="finish", past_participle="finished", simple_past="finished", present_participle="finishing"),
    "fit": Conjugation(base="fit", past_participle="fit", simple_past="fit", present_participle="fitting"),
    "fix": Conjugation(base="fix", past_participle="fixed", simple_past="fixed", present_participle="fixing"),
    "flag": Conjugation(base="flag", past_participle="flagged", simple_past="flagged", present_participle="flagging"),
    "flush": Conjugation(base="flush", past_participle="flushed", simple_past="flushed", present_participle="flushing"),
    "fly": Conjugation(base="fly", past_participle="flown", simple_past="flew", present_participle="flying"),
    "follow": Conjugation(base="follow", past_participle="followed", simple_past="followed", present_participle="following"),
    "forget": Conjugation(base="forget", past_participle="forgotten", simple_past="forgot", present_participle="forgetting"),
    "forgive": Conjugation(base="forgive", past_participle="forgiven", simple_past="forgave", present_participle="forgiving"),
    "format": Conjugation(base="format", past_participle="formatted", simple_past="formatted", present_participle="formatting"),
    "forward": Conjugation(base="forward", past_participle="forwarded", simple_past="forwarded", present_participle="forwarding"),
    "freeze": Conjugation(base="freeze", past_participle="frozen", simple_past="froze", present_participle="freezing"),
    # G
    "generate": Conjugation(base="generate", past_participle="generated", simple_past="generated", present_participle="generating"),
    "get": Conjugation(base="get", past_participle="got", simple_past="got", present_participle="getting"),
    "give": Conjugation(base="give", past_participle="given", simple_past="gave", present_participle="giving"),
    "go": Conjugation(base="go", past_participle="gone", simple_past="went", present_participle="going"),
    "grant": Conjugation(base="grant", past_participle="granted", simple_past="granted", present_participle="granting"),
    "group": Conjugation(base="group", past_participle="grouped", simple_past="grouped", present_participle="grouping"),
    "grow": Conjugation(base="grow", past_participle="grown", simple_past="grew", present_participle="growing"),
    "guide": Conjugation(base="guide", past_participle="guided", simple_past="guided", present_participle="guiding"),
    # H
    "handle": Conjugation(base="handle", past_participle="handled", simple_past="handled", present_participle="handling"),
    "happen": Conjugation(base="happen", past_participle="happened", simple_past="happened", present_participle="happening"),
    "hash": Conjugation(base="hash", past_participle="hashed", simple_past="hashed", present_participle="hashing"),
    "have": Conjugation(base="have", past_participle="had", simple_past="had", present_participle="having"),
    "hear": Conjugation(base="hear", past_participle="heard", simple_past="heard", present_participle="hearing"),
    "help": Conjugation(base="help", past_participle="helped", simple_past="helped", present_participle="helping"),
    "hide": Conjugation(base="hide", past_participle="hidden", simple_past="hid", present_participle="hiding"),
    "hit": Conjugation(base="hit", past_participle="hit", simple_past="hit", present_participle="hitting"),
    "hold": Conjugation(base="hold", past_participle="held", simple_past="held", present_participle="holding"),
    "hurt": Conjugation(base="hurt", past_participle="hurt", simple_past="hurt", present_participle="hurting"),
    # I
    "identify": Conjugation(base="identify", past_participle="identified", simple_past="identified", present_participle="identifying"),
    "implement": Conjugation(base="implement", past_participle="implemented", simple_past="implemented", present_participle="implementing"),
    "import": Conjugation(base="import", past_participle="imported", simple_past="imported", present_participle="importing"),
    "improve": Conjugation(base="improve", past_participle="improved", simple_past="improved", present_participle="improving"),
    "include": Conjugation(base="include", past_participle="included", simple_past="included", present_participle="including"),
    "increase": Conjugation(base="increase", past_participle="increased", simple_past="increased", present_participle="increasing"),
    "index": Conjugation(base="index", past_participle="indexed", simple_past="indexed", present_participle="indexing"),
    "indicate": Conjugation(base="indicate", past_participle="indicated", simple_past="indicated", present_participle="indicating"),
    "inherit": Conjugation(base="inherit", past_participle="inherited", simple_past="inherited", present_participle="inheriting"),
    "initialise": Conjugation(base="initialise", past_participle="initialised", simple_past="initialised", present_participle="initialising"),
    "initialize": Conjugation(base="initialize", past_participle="initialized", simple_past="initialized", present_participle="initializing"),
    "initiate": Conjugation(base="initiate", past_participle="initiated", simple_past="initiated", present_participle="initiating"),
    "inject": Conjugation(base="inject", past_participle="injected", simple_past="injected", present_participle="injecting"),
    "insert": Conjugation(base="insert", past_participle="inserted", simple_past="inserted", present_participle="inserting"),
    "inspect": Conjugation(base="inspect", past_participle="inspected", simple_past="inspected", present_participle="inspecting"),
    "install": Conjugation(base="install", past_participle="installed", simple_past="installed", present_participle="installing"),
    "instantiate": Conjugation(base="instantiate", past_participle="instantiated", simple_past="instantiated", present_participle="instantiating"),
    "integrate": Conjugation(base="integrate", past_participle="integrated", simple_past="integrated", present_participle="integrating"),
    "interrupt": Conjugation(base="interrupt", past_participle="interrupted", simple_past="interrupted", present_participle="interrupting"),
    "invoke": Conjugation(base="invoke", past_participle="invoked", simple_past="invoked", present_participle="invoking"),
    "iterate": Conjugation(base="iterate", past_participle="iterated", simple_past="iterated", present_participle="iterating"),
    # J
    "join": Conjugation(base="join", past_participle="joined", simple_past="joined", present_participle="joining"),
    # K
    "keep": Conjugation(base="keep", past_participle="kept", simple_past="kept", present_participle="keeping"),
    "kill": Conjugation(base="kill", past_participle="killed", simple_past="killed", present_participle="killing"),
    "know": Conjugation(base="know", past_participle="known", simple_past="knew", present_participle="knowing"),
    # L
    "launch": Conjugation(base="launch", past_participle="launched", simple_past="launched", present_participle="launching"),
    "lay": Conjugation(base="lay", past_participle="laid", simple_past="laid", present_participle="laying"),
    "lead": Conjugation(base="lead", past_participle="led", simple_past="led", present_participle="leading"),
    "learn": Conjugation(base="learn", past_participle="learned", simple_past="learned", present_participle="learning"),
    "leave": Conjugation(base="leave", past_participle="left", simple_past="left", present_participle="leaving"),
    "let": Conjugation(base="let", past_participle="let", simple_past="let", present_participle="letting"),
    "link": Conjugation(base="link", past_participle="linked", simple_past="linked", present_participle="linking"),
    "list": Conjugation(base="list", past_participle="listed", simple_past="listed", present_participle="listing"),
    "listen": Conjugation(base="listen", past_participle="listened", simple_past="listened", present_participle="listening"),
    "load": Conjugation(base="load", past_participle="loaded", simple_past="loaded", present_participle="loading"),
    "lock": Conjugation(base="lock", past_participle="locked", simple_past="locked", present_participle="locking"),
    "log": Conjugation(base="log", past_participle="logged", simple_past="logged", present_participle="logging"),
    "loop": Conjugation(base="loop", past_participle="looped", simple_past="looped", present_participle="looping"),
    "lose": Conjugation(base="lose", past_participle="lost", simple_past="lost", present_participle="losing"),
    # M
    "make": Conjugation(base="make", past_participle="made", simple_past="made", present_participle="making"),
    "manage": Conjugation(base="manage", past_participle="managed", simple_past="managed", present_participle="managing"),
    "map": Conjugation(base="map", past_participle="mapped", simple_past="mapped", present_participle="mapping"),
    "mark": Conjugation(base="mark", past_participle="marked", simple_past="marked", present_participle="marking"),
    "match": Conjugation(base="match", past_participle="matched", simple_past="matched", present_participle="matching"),
    "meet": Conjugation(base="meet", past_participle="met", simple_past="met", present_participle="meeting"),
    "merge": Conjugation(base="merge", past_participle="merged", simple_past="merged", present_participle="merging"),
    "modify": Conjugation(base="modify", past_participle="modified", simple_past="modified", present_participle="modifying"),
    "monitor": Conjugation(base="monitor", past_participle="monitored", simple_past="monitored", present_participle="monitoring"),
    "mount": Conjugation(base="mount", past_participle="mounted", simple_past="mounted", present_participle="mounting"),
    "move": Conjugation(base="move", past_participle="moved", simple_past="moved", present_participle="moving"),
    # N
    "name": Conjugation(base="name", past_participle="named", simple_past="named", present_participle="naming"),
    "navigate": Conjugation(base="navigate", past_participle="navigated", simple_past="navigated", present_participle="navigating"),
    "need": Conjugation(base="need", past_participle="needed", simple_past="needed", present_participle="needing"),
    "notify": Conjugation(base="notify", past_participle="notified", simple_past="notified", present_participle="notifying"),
    # O
    "observe": Conjugation(base="observe", past_participle="observed", simple_past="observed", present_participle="observing"),
    "occur": Conjugation(base="occur", past_participle="occurred", simple_past="occurred", present_participle="occurring"),
    "open": Conjugation(base="open", past_participle="opened", simple_past="opened", present_participle="opening"),
    "optimise": Conjugation(base="optimise", past_participle="optimised", simple_past="optimised", present_participle="optimising"),
    "optimize": Conjugation(base="optimize", past_participle="optimized", simple_past="optimized", present_participle="optimizing"),
    "order": Conjugation(base="order", past_participle="ordered", simple_past="ordered", present_participle="ordering"),
    "organise": Conjugation(base="organise", past_participle="organised", simple_past="organised", present_participle="organising"),
    "organize": Conjugation(base="organize", past_participle="organized", simple_past="organized", present_participle="organizing"),
    "output": Conjugation(base="output", past_participle="outputted", simple_past="outputted", present_participle="outputting"),
    "override": Conjugation(base="override", past_participle="overridden", simple_past="overrode", present_participle="overriding"),
    # P
    "paginate": Conjugation(base="paginate", past_participle="paginated", simple_past="paginated", present_participle="paginating"),
    "parse": Conjugation(base="parse", past_participle="parsed", simple_past="parsed", present_participle="parsing"),
    "pass": Conjugation(base="pass", past_participle="passed", simple_past="passed", present_participle="passing"),
    "paste": Conjugation(base="paste", past_participle="pasted", simple_past="pasted", present_participle="pasting"),
    "patch": Conjugation(base="patch", past_participle="patched", simple_past="patched", present_participle="patching"),
    "pay": Conjugation(base="pay", past_participle="paid", simple_past="paid", present_participle="paying"),
    "perform": Conjugation(base="perform", past_participle="performed", simple_past="performed", present_participle="performing"),
    "persist": Conjugation(base="persist", past_participle="persisted", simple_past="persisted", present_participle="persisting"),
    "ping": Conjugation(base="ping", past_participle="pinged", simple_past="pinged", present_participle="pinging"),
    "pipe": Conjugation(base="pipe", past_participle="piped", simple_past="piped", present_participle="piping"),
    "plan": Conjugation(base="plan", past_participle="planned", simple_past="planned", present_participle="planning"),
    "play": Conjugation(base="play", past_participle="played", simple_past="played", present_participle="playing"),
    "plot": Conjugation(base="plot", past_participle="plotted", simple_past="plotted", present_participle="plotting"),
    "point": Conjugation(base="point", past_participle="pointed", simple_past="pointed", present_participle="pointing"),
    "poll": Conjugation(base="poll", past_participle="polled", simple_past="polled", present_participle="polling"),
    "populate": Conjugation(base="populate", past_participle="populated", simple_past="populated", present_participle="populating"),
    "post": Conjugation(base="post", past_participle="posted", simple_past="posted", present_participle="posting"),
    "preload": Conjugation(base="preload", past_participle="preloaded", simple_past="preloaded", present_participle="preloading"),
    "print": Conjugation(base="print", past_participle="printed", simple_past="printed", present_participle="printing"),
    "process": Conjugation(base="process", past_participle="processed", simple_past="processed", present_participle="processing"),
    "publish": Conjugation(base="publish", past_participle="published", simple_past="published", present_participle="publishing"),
    "push": Conjugation(base="push", past_participle="pushed", simple_past="pushed", present_participle="pushing"),
    "put": Conjugation(base="put", past_participle="put", simple_past="put", present_participle="putting"),
    # Q
    "query": Conjugation(base="query", past_participle="queried", simple_past="queried", present_participle="querying"),
    "queue": Conjugation(base="queue", past_participle="queued", simple_past="queued", present_participle="queuing"),
    # R
    "raise": Conjugation(base="raise", past_participle="raised", simple_past="raised", present_participle="raising"),
    "read": Conjugation(base="read", past_participle="read", simple_past="read", present_participle="reading"),
    "receive": Conjugation(base="receive", past_participle="received", simple_past="received", present_participle="receiving"),
    "reduce": Conjugation(base="reduce", past_participle="reduced", simple_past="reduced", present_participle="reducing"),
    "refactor": Conjugation(base="refactor", past_participle="refactored", simple_past="refactored", present_participle="refactoring"),
    "refresh": Conjugation(base="refresh", past_participle="refreshed", simple_past="refreshed", present_participle="refreshing"),
    "register": Conjugation(base="register", past_participle="registered", simple_past="registered", present_participle="registering"),
    "reject": Conjugation(base="reject", past_participle="rejected", simple_past="rejected", present_participle="rejecting"),
    "reload": Conjugation(base="reload", past_participle="reloaded", simple_past="reloaded", present_participle="reloading"),
    "remove": Conjugation(base="remove", past_participle="removed", simple_past="removed", present_participle="removing"),
    "rename": Conjugation(base="rename", past_participle="renamed", simple_past="renamed", present_participle="renaming"),
    "render": Conjugation(base="render", past_participle="rendered", simple_past="rendered", present_participle="rendering"),
    "replace": Conjugation(base="replace", past_participle="replaced", simple_past="replaced", present_participle="replacing"),
    "request": Conjugation(base="request", past_participle="requested", simple_past="requested", present_participle="requesting"),
    "reset": Conjugation(base="reset", past_participle="reset", simple_past="reset", present_participle="resetting"),
    "resolve": Conjugation(base="resolve", past_participle="resolved", simple_past="resolved", present_participle="resolving"),
    "restart": Conjugation(base="restart", past_participle="restarted", simple_past="restarted", present_participle="restarting"),
    "restore": Conjugation(base="restore", past_participle="restored", simple_past="restored", present_participle="restoring"),
    "retry": Conjugation(base="retry", past_participle="retried", simple_past="retried", present_participle="retrying"),
    "return": Conjugation(base="return", past_participle="returned", simple_past="returned", present_participle="returning"),
    "revert": Conjugation(base="revert", past_participle="reverted", simple_past="reverted", present_participle="reverting"),
    "revoke": Conjugation(base="revoke", past_participle="revoked", simple_past="revoked", present_participle="revoking"),
    "route": Conjugation(base="route", past_participle="routed", simple_past="routed", present_participle="routing"),
    "run": Conjugation(base="run", past_participle="run", simple_past="ran", present_participle="running"),
    # S
    "save": Conjugation(base="save", past_participle="saved", simple_past="saved", present_participle="saving"),
    "scan": Conjugation(base="scan", past_participle="scanned", simple_past="scanned", present_participle="scanning"),
    "schedule": Conjugation(base="schedule", past_participle="scheduled", simple_past="scheduled", present_participle="scheduling"),
    "scroll": Conjugation(base="scroll", past_participle="scrolled", simple_past="scrolled", present_participle="scrolling"),
    "search": Conjugation(base="search", past_participle="searched", simple_past="searched", present_participle="searching"),
    "select": Conjugation(base="select", past_participle="selected", simple_past="selected", present_participle="selecting"),
    "send": Conjugation(base="send", past_participle="sent", simple_past="sent", present_participle="sending"),
    "serialise": Conjugation(base="serialise", past_participle="serialised", simple_past="serialised", present_participle="serialising"),
    "serialize": Conjugation(base="serialize", past_participle="serialized", simple_past="serialized", present_participle="serializing"),
    "serve": Conjugation(base="serve", past_participle="served", simple_past="served", present_participle="serving"),
    "set": Conjugation(base="set", past_participle="set", simple_past="set", present_participle="setting"),
    "show": Conjugation(base="show", past_participle="shown", simple_past="showed", present_participle="showing"),
    "skip": Conjugation(base="skip", past_participle="skipped", simple_past="skipped", present_participle="skipping"),
    "snapshot": Conjugation(base="snapshot", past_participle="snapshotted", simple_past="snapshotted", present_participle="snapshotting"),
    "sort": Conjugation(base="sort", past_participle="sorted", simple_past="sorted", present_participle="sorting"),
    "spawn": Conjugation(base="spawn", past_participle="spawned", simple_past="spawned", present_participle="spawning"),
    "split": Conjugation(base="split", past_participle="split", simple_past="split", present_participle="splitting"),
    "start": Conjugation(base="start", past_participle="started", simple_past="started", present_participle="starting"),
    "stop": Conjugation(base="stop", past_participle="stopped", simple_past="stopped", present_participle="stopping"),
    "store": Conjugation(base="store", past_participle="stored", simple_past="stored", present_participle="storing"),
    "stream": Conjugation(base="stream", past_participle="streamed", simple_past="streamed", present_participle="streaming"),
    "submit": Conjugation(base="submit", past_participle="submitted", simple_past="submitted", present_participle="submitting"),
    "subscribe": Conjugation(base="subscribe", past_participle="subscribed", simple_past="subscribed", present_participle="subscribing"),
    "support": Conjugation(base="support", past_participle="supported", simple_past="supported", present_participle="supporting"),
    "swap": Conjugation(base="swap", past_participle="swapped", simple_past="swapped", present_participle="swapping"),
    "swim": Conjugation(base="swim", past_participle="swum", simple_past="swam", present_participle="swimming"),
    "switch": Conjugation(base="switch", past_participle="switched", simple_past="switched", present_participle="switching"),
    "sync": Conjugation(base="sync", past_participle="synced", simple_past="synced", present_participle="syncing"),
    "synchronise": Conjugation(base="synchronise", past_participle="synchronised", simple_past="synchronised", present_participle="synchronising"),
    "synchronize": Conjugation(base="synchronize", past_participle="synchronized", simple_past="synchronized", present_participle="synchronizing"),
    # T
    "terminate": Conjugation(base="terminate", past_participle="terminated", simple_past="terminated", present_participle="terminating"),
    "test": Conjugation(base="test", past_participle="tested", simple_past="tested", present_participle="testing"),
    "throw": Conjugation(base="throw", past_participle="thrown", simple_past="threw", present_participle="throwing"),
    "toggle": Conjugation(base="toggle", past_participle="toggled", simple_past="toggled", present_participle="toggling"),
    "track": Conjugation(base="track", past_participle="tracked", simple_past="tracked", present_participle="tracking"),
    "transform": Conjugation(base="transform", past_participle="transformed", simple_past="transformed", present_participle="transforming"),
    "translate": Conjugation(base="translate", past_participle="translated", simple_past="translated", present_participle="translating"),
    "transmit": Conjugation(base="transmit", past_participle="transmitted", simple_past="transmitted", present_participle="transmitting"),
    "trigger": Conjugation(base="trigger", past_participle="triggered", simple_past="triggered", present_participle="triggering"),
    "truncate": Conjugation(base="truncate", past_participle="truncated", simple_past="truncated", present_participle="truncating"),
    "try": Conjugation(base="try", past_participle="tried", simple_past="tried", present_participle="trying"),
    # U
    "undo": Conjugation(base="undo", past_participle="undone", simple_past="undid", present_participle="undoing"),
    "uninstall": Conjugation(base="uninstall", past_participle="uninstalled", simple_past="uninstalled", present_participle="uninstalling"),
    "unlock": Conjugation(base="unlock", past_participle="unlocked", simple_past="unlocked", present_participle="unlocking"),
    "unsubscribe": Conjugation(base="unsubscribe", past_participle="unsubscribed", simple_past="unsubscribed", present_participle="unsubscribing"),
    "unwrap": Conjugation(base="unwrap", past_participle="unwrapped", simple_past="unwrapped", present_participle="unwrapping"),
    "update": Conjugation(base="update", past_participle="updated", simple_past="updated", present_participle="updating"),
    "upload": Conjugation(base="upload", past_participle="uploaded", simple_past="uploaded", present_participle="uploading"),
    "use": Conjugation(base="use", past_participle="used", simple_past="used", present_participle="using"),
    # V
    "validate": Conjugation(base="validate", past_participle="validated", simple_past="validated", present_participle="validating"),
    "verify": Conjugation(base="verify", past_participle="verified", simple_past="verified", present_participle="verifying"),
    # W
    "wait": Conjugation(base="wait", past_participle="waited", simple_past="waited", present_participle="waiting"),
    "wake": Conjugation(base="wake", past_participle="awoken", simple_past="woke", present_participle="waking"),
    "watch": Conjugation(base="watch", past_participle="watched", simple_past="watched", present_participle="watching"),
    "win": Conjugation(base="win", past_participle="won", simple_past="won", present_participle="winning"),
    "wrap": Conjugation(base="wrap", past_participle="wrapped", simple_past="wrapped", present_participle="wrapping"),
    "write": Conjugation(base="write", past_participle="written", simple_past="wrote", present_participle="writing"),
}

def _match_case(word: str, template: str) -> str:
    """Match the case of the template word in the given word."""
    if template.isupper():
        return word.upper()
    if template.islower():
        return word.lower()
    rtn = ''.join(w.upper() if t.isupper() else w.lower() for w, t in zip(word, template))
    if len(word) > len(template):
        rtn += word[len(template):]
    return rtn

def past_participle(word: str) -> str | None:
    c = _conjugation_map.get(word.lower())
    return _match_case(c.past_participle, word) if c else None

def simple_past(word: str) -> str | None:
    c = _conjugation_map.get(word.lower())
    return _match_case(c.simple_past, word) if c else None

def present_participle(word: str) -> str | None:
    c = _conjugation_map.get(word.lower())
    return _match_case(c.present_participle, word) if c else None

@dataclass
class Conjugator:
    sentence: str

    def to_past(self) -> str:
        return ' '.join(simple_past(word) or word for word in self.sentence.split())
    
    def to_present_continuous(self) -> str:
        return ' '.join(present_participle(word) or word for word in self.sentence.split())


if __name__ == "__main__":
    test_sentence = "Do the thing and then undo it"
    conjugator = Conjugator(test_sentence)
    print(f"Original: {test_sentence}")
    print(f"Past: {conjugator.to_past()}")
    print(f"Present Continuous: {conjugator.to_present_continuous()}")